version: '3.4'

services:
  node:
    image: node:11
    volumes:
      - ./node:/app
      - ./data/node/npm:/root/.npm
      - /tmp/devday/node:/tmp
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run start
    ports:
      - 7000:3000

  postgres:
    image: postgres:12
    restart: always
    ports:
      - "7001:5432"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - /tmp/devday/postgres:/tmp
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "7002:8080"
    volumes:
    - /tmp/devday/graphql-engine:/tmp
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: verysecret